accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accounts.views import SubmittableloginView, SignUpView, SubmittablePasswordChangeView, ProfileDetailedView, \
    ProfileUpdateView

app_name = "accounts"




urlpatterns = [
    path("login/", SubmittableloginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("sign-up/", SignUpView.as_view(), name="sign_up"),
    path("password-change/", SubmittablePasswordChangeView.as_view(), name="password_change"),
    path("profile/<int:pk>/", ProfileDetailedView.as_view(), name="profile_view"),
    path("profile/<int:pk>/update/", ProfileUpdateView.as_view(), name="profile_update"),
]

hollymovies/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

from accounts.models import Profile
from viewer.forms import MovieForm
from viewer.views import search, MoviesView, MovieCreateView, Hello, Contact, GenreCreateView, GreetingView, \
    MovieUpdateView, MovieDeleteView, MovieDetailView, GenreListView, GenreUpdateView, GenreDeleteView
from viewer.models import Genre, Movie
from viewer.admin import MovieAdmin, GenreAdmin

admin.site.register(Genre, GenreAdmin)
admin.site.register(Movie, MovieAdmin)
admin.site.register(Profile)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include('accounts.urls')),
    path("search/", search, name="search"),
    path("movies/new", MovieCreateView.as_view(success_url="/movies/"), name="create_movie"),
    path("movies/<int:pk>", MovieDetailView.as_view(), name="read_movie"),
    path("movies/<int:pk>/update", MovieUpdateView.as_view(), name="update_movie"),
    path("movies/<int:pk>/delete", MovieDeleteView.as_view(), name="delete_movie"),
    path("movies/", MoviesView.as_view(), name="movies"),
    path("genres/", GenreListView.as_view(), name="genres"),
    path("genres/<int:pk>/update", GenreUpdateView.as_view(), name="update_genre"),
    path("genres/<int:pk>/delete", GenreDeleteView.as_view(), name="delete_genre"),

    path("greeting/", GreetingView.as_view(greeting="Hello"), name="greeting"),
    path("new_genre/", GenreCreateView.as_view(success_url="/new_genre"), name="create_genre"),
    path("contact/", Contact.as_view(), name="contact"),
    path("", Hello.as_view(), name="hello"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viewer/models.py
from PIL import Image
from django.db.models import Model, CharField, ForeignKey, DO_NOTHING, IntegerField, DateField, TextField, \
    DateTimeField, ImageField


class Genre(Model):
    name = CharField(max_length=128)

    def __str__(self):
        return f"{self.name}"
    #
    # def __hash__(self):
    #     return hash(str(self))


class Movie(Model):
    title = CharField(max_length=128)
    image = ImageField(default="movie_default.jpg", upload_to="movies_thumbnails")
    genre = ForeignKey(Genre, on_delete=DO_NOTHING)
    rating = IntegerField()
    released = DateField()
    description = TextField()
    created = DateTimeField(auto_now_add=True)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super(Movie, self).save()

        img = Image.open(self.image.path)
        if img.height > 600 or img.width > 600:
            output_size = (600, 600)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def __str__(self):
        return f"{self.title}; {self.released.year}"

viewer/forms.py
from django.core.exceptions import ValidationError
from django.forms import (
    Form,
    CharField,
    ModelChoiceField,
    IntegerField,
    DateField,
    Textarea,
    SelectDateWidget,
    NumberInput, ModelForm,
)
from datetime import date
from viewer.models import Genre, Movie


def capitalize_validator(value):
    if value[0].islower():
        raise ValidationError("Value must be capitalized.")


def dupa_validator(value: str) -> None:
    if 'dupa' in value.lower():
        raise ValidationError("Dupa is not allowed in this field.")


def unique_validator(value: str) -> None:
    splitted_val = value.strip('.').strip(',').strip('!').strip('?').lower().split(" ")
    if len(splitted_val) != len(set(splitted_val)):
        raise ValidationError("Only unique words allowed.")


class PastDate(DateField):
    def validate(self, value):
        super().validate(value)
        if value >= date.today():
            raise ValidationError("Future dates are not allowed.")

    def clean(self, value):
        result = super().clean(value)
        return date(year=result.year, month=result.month, day=1)


class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

    title = CharField(max_length=128, validators=[capitalize_validator])
    released = PastDate(widget=NumberInput(attrs={"type": "date"}))
    description = CharField(widget=Textarea, required=False, validators=[])

    def clean(self):
        result = super().clean()
        if result['genre'].name == 'Comedy' and result['rating'] > 6:
            self.add_error("genre", f"Can't be Comedy if {result['rating']}.")
            self.add_error("rating", f"Cant't be {result['rating']} if genre is Comedy.")
            # self.add_error("rating", f"Cant't be {result['rating']} if genre is {result['genre'].name}.") !!!Czemu nie dziala??????
            raise ValidationError("Comedies are not so good to be rated above 6.")
        return result


class GenreForm(ModelForm):
    class Meta:
        model = Genre
        fields = '__all__'
    name = CharField(max_length=128)

viewer/views.py
from logging import getLogger

from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, FormView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin

from viewer.forms import MovieForm, GenreForm
from viewer.models import Movie, Genre

LOG = getLogger()


def search(request):
    title = request.GET.get("title")
    if title is None:
        return render(request, "search.html", context={"data": [], "count": 0})
    data = Movie.objects.filter(title__contains=title)
    return render(request, "search.html", context={"data": data, "count": data.count})


class StaffRequiredMixin(UserPassesTestMixin):

    def test_func(self):
        return self.request.user.is_staff


class Hello(TemplateView):
    template_name = "hello.html"


class Contact(TemplateView):
    template_name = "contact.html"


class MoviesView(ListView):
    template_name = "movies.html"
    model = Movie
    paginate_by = 5


class GenreListView(ListView):
    template_name = "genres.html"
    model = Genre


class MovieCreateView(PermissionRequiredMixin, CreateView):
    template_name = "forms/form.html"
    form_class = MovieForm
    success_url = reverse_lazy("movies")
    permission_required = "viewer.add_movie"

    def form_invalid(self, form):
        LOG.warning("User provided invalid data.")
        return super().form_invalid(form)

    # def form_valid(self, form):
    #     result = super().form_valid(form)
    #     cleaned_data = form.cleaned_data
    #     Movie.objects.create(
    #         title=cleaned_data["title"],
    #         genre=cleaned_data["genre"],
    #         rating=cleaned_data["rating"],
    #         released=cleaned_data["released"],
    #         description=cleaned_data["description"],
    #     )
    #     return result


class MovieUpdateView(PermissionRequiredMixin, StaffRequiredMixin, UpdateView):
    template_name = 'forms/form.html'
    form_class = MovieForm
    model = Movie
    success_url = reverse_lazy('movies')
    permission_required = "viewer.change_movie"

    def form_invalid(self, form):
        LOG.warning("User provided invalid data while updating.")
        return super().form_invalid(form)


class MovieDeleteView(PermissionRequiredMixin, StaffRequiredMixin, DeleteView):
    template_name = 'forms/delete_movie_form.html'
    model = Movie
    success_url = reverse_lazy('movies')
    permission_required = "viewer.delete_movie"

    def test_func(self):
        return super().test_func() and self.request.user.is_superuser

    # def get(self, request, pk):
    #     if not Movie.objects.filter(id=pk).exists():
    #         return HttpResponse('Object does not exists.')
    #     return super().get(request)


class GenreCreateView(PermissionRequiredMixin, FormView):
    template_name = "forms/form.html"
    form_class = GenreForm
    success_url = reverse_lazy("create_genre")
    permission_required = 'viewer.add_genre'

    def form_valid(self, form):
        result = super().form_valid(form)
        cleaned_data = form.cleaned_data
        Genre.objects.create(
            name=cleaned_data["name"],
        )
        return result

    # def get(self, request):
    #     return render(request, 'movies.html', context={'movies': Movie.objects.all()})


class GenreUpdateView(StaffRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = 'forms/form.html'
    form_class = GenreForm
    model = Genre
    success_url = reverse_lazy('genres')
    permission_required = "viewer.change_genre"

    # def form_invalid(self, form):
    #     LOG.warning("User provided invalid data while updating.")
    #     return super().form_invalid(form)


class GenreDeleteView(DeleteView):
    template_name = 'forms/delete_genre_form.html'
    model = Genre
    success_url = reverse_lazy('genres')

    # def get(self, request, pk):
    #     if not Genre.objects.filter(id=pk).exists():
    #         return HttpResponse('Object does not exists.')
    #     return super().get(request)


class GreetingView(View):
    greeting = "Good morning"

    def get(self, request):
        return HttpResponse(self.greeting)


class MovieDetailView(DetailView):
    template_name = "movie_detailed_view.html"
    model = Movie

viewer/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hollymovies</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <style>
    h1 {
      margin: 10px;
    }
    .account-img {
        height: 100px;
        width: 100px;
    }
    .movie-img {
        height: 200px;
        width: 200px;
    }
    p {
      margin: 10px;
    }
  </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'hello' %}">Hollymovies</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'movies' %}">Movies</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'search' %}">Search</a>
        </li>
          {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'create_movie' %}">Add Movie</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'create_genre' %}">Add Genre</a>
        </li>
          {% endif %}
        {% if user.is_superuser %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'genres' %}">Genres</a>
        </li>
      {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
        </li>
      </ul>
    </div>
      <div class="nav-item dropdown">
          {% if user.is_authenticated %}
            <a class="nav-link dropdown-toggle" href="#" id="dropdownAuthenticatedUserMenu" data-bs-toggle="dropdown">
            {% if user.first_name %}Hello, {{ user.first_name }}!
            {% else %}Hello, {{ user.username }} with id {{ user.id }}!{% endif %}
            </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownAuthenticatedUserMenu">
                <a class="dropdown-item text-right" href="{% url 'accounts:logout' %}">Logout</a>
                <a class="dropdown-item text-right" href="{% url 'accounts:password_change' %}">Change password</a>
                <a class="dropdown-item text-right" href="{% url 'accounts:profile_view' user.id %}">View profile</a>
              </div>
          {% else %}
            <a class="nav-link active dropdown-toggle" href="#" id="dropdownUserMenu" data-bs-toggle="dropdown">
                You are not logged in.
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownUserMenu">
                <a class="dropdown-item text-right" href="{% url 'accounts:login' %}">Login</a>
                <a class="dropdown-item text-right" href="{% url 'accounts:sign_up' %}">Sign Up</a>
            </div>
          {% endif %}
      </div>
  </div>
</nav>
<div class="container">
  {% block content %}
  {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

viewer/templates/contact.html
{% extends "base.html" %}

{% block content %}
<h1>Contact us!</h1>
<p>Phone: +12 345 67 89</p>
<p>email: email@example.com</p>
<!--<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d581.2859174844592!2d18.59466862922689!3d54.354442180317385!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46fd746404047c49%3A0xe4fbe8c06a77fa40!2sPiecki-Migowo%2C%2080-171%20Gda%C5%84sk!5e0!3m2!1spl!2spl!4v1643464429106!5m2!1spl!2spl" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy"></iframe>-->
{% endblock %}

viewer/templates/genres.html
{% extends "base.html" %}

{% block content %}

  <div class="card-header">
    List of available genres:
  </div>
  <table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
    </tr>
  </thead>
  <tbody>
        {% for genre in object_list %}
          <tr>
            <th scope="row">{{genre.id}}</th>
            <td>{{genre.name}} <a class="btn btn-success btn-sm float-end" href="{% url "update_genre" genre.id %}">Update</a> </td>
{#          <td><a class="btn btn-danger" href="{% url 'delete_movie' movie.id %}">Delete movie</a></td>#}
          </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

viewer/templates/hello.html
{% extends "base.html" %}

{% block content %}
<h1>Wellcome to hollywood movies!</h1>
<a class="btn btn-primary btn-sm" href="{% url 'greeting' %}">Hello</a>
{% endblock %}

viewer/templates/movie_detailed_view.html
{% extends 'base.html' %}

{% block content %}
    <div class="container py-4">
        <h2>{{ movie.title }}</h2>
        <img class="rounded-circle movie-img" src="{{ movie.image.url}}">
        <small> {{ movie.released.year }} - {{ movie.genre }} - {{ movie.rating }}/10 <i class="fa fa-star"></i></small>
        <p><b>Released: </b>{{ movie.released | date:"d E Y" }}</p>
        <hr>
        <p>{{ movie.description }}</p>
        <small>Description length: {{ movie.description|length }}</small>
        <hr>
        {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url "update_movie" movie.id %}">Update</a>
        <a class="btn btn-danger" href="{% url "delete_movie" movie.id %}">Delete</a>
    {% endif %}
    </div>

{% endblock %}

viewer/templates/movies.html
{% extends "base.html" %}

{% block content %}


  <div class="card-header">
    List of available movies:
  </div>
  <table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Title</th>
      <th scope="col">Genre</th>
      <th scope="col">First Released</th>
      <th scope="col">Rating</th>
      <th scope="col">Description</th>
    </tr>
  </thead>
  <tbody>
        {% for movie in object_list %}
          <tr onclick="window.location='{% url 'read_movie' movie.id %}'">
            <th scope="row">{{movie.id}}</th>
            <td>{{movie.title}}</td>
            <td>{{movie.genre}}</td>
            <td>{{movie.released}}</td>
            <td>{{movie.rating}}</td>
            <td>{{movie.description}}</td>
{#          <td><a class="btn btn-danger" href="{% url 'delete_movie' movie.id %}">Delete movie</a></td>#}
          </tr>
  {% endfor %}
  </tbody>
</table>
    {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-secondary mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-secondary mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% else %}
            <a class="btn btn-outline-secondary mb-4 disabled">First</a>
            <a class="btn btn-outline-secondary mb-4 disabled">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-secondary mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-secondary mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-secondary mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-secondary mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% else %}
            <a class="btn btn-outline-secondary mb-4 disabled">Next</a>
            <a class="btn btn-outline-secondary mb-4 disabled">Last</a>

        {% endif %}




    {% endif %}
{% endblock %}

viewer/templates/search.html
{% extends "base.html" %}

{% block content %}
<div class="input-group mb-3">
  <input type="text" class="form-control" placeholder="Title" aria-label="Title" aria-describedby="button-addon2">
  <button class="btn btn-outline-secondary" type="button" id="button-addon2">Search</button>
</div>
<p class="card">
  {% if count != 0 %}
  <table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Title</th>
      <th scope="col">Genre</th>
      <th scope="col">First Released</th>
      <th scope="col">Rating</th>
      <th scope="col">Description</th>
    </tr>
  </thead>
  <tbody>
        {% for movie in data %}
          <tr>
            <th scope="row">{{movie.id}}</th>
            <td>{{movie.title}}</td>
            <td>{{movie.genre}}</td>
            <td>{{movie.released}}</td>
            <td>{{movie.rating}}</td>
            <td>{{movie.description}}</td>
          </tr>
  {% endfor %}
  </tbody>
</table>
  {%endif%}<p> Querry returned {{count}} result{{ count|pluralize }}.</p>

{% endblock content%}